name: Run and deploy Nilearn benchmarks

on:
  push:
    branches:
      - main

jobs:
  benchmark:
    if: contains(github.event.head_commit.message, '[bm]')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install asv
        run: |
          pip install --upgrade pip
          pip install asv
      - name: Pull previous results from benchmarks repo on nilearn org
        run: |
          git clone https://github.com/nilearn/benchmarks.git benchmarks_repo
          cp -r benchmarks_repo/results .
      - name: Run tracking benchmarks until 0.9.0
        run: |
          asv machine --yes
          asv run -ev --append-samples
      - name: Create html with all results
        run: |
          asv publish
      - uses: actions/upload-artifact@v4
        with:
          name: asv_benchmark_results
          path: |
            ./env
            ./html
            ./results
          compression-level: 9
      - name: Push new results back to benchmarks repo on nilearn org
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          cp -r ./results benchmarks_repo/
          cp -r ./html/* benchmarks_repo/
          cd benchmarks_repo
          git add .
          git commit -m "Update benchmark results and HTML [skip ci]"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/nilearn/benchmarks.git
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/main'
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
