name: Run and deploy Nilearn benchmarks

on:
  push:
    branches:
      - main

jobs:
  benchmark:
    if: contains(github.event.head_commit.message, '[bm]')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install asv
        run: |
          pip install --upgrade pip
          pip install asv
      - name: Add SSH key
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            echo "${{ secrets.ACTIONS_SSH_DEPLOY }}" > ~/.ssh/github_actions
            chmod 600 ~/.ssh/github_actions
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add ~/.ssh/github_actions
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
      - name: Pull previous results from benchmarks repo on nilearn org
        env:
              SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          git clone git@github.com:nilearn/benchmarks.git benchmarks_repo
          cp -r benchmarks_repo/results .
      - name: Get all the machine info
        run: |
          asv machine --yes 2>&1 | tee log_$GITHUB_RUN_ID
      - name: Edit asv-machine.json to a custom machine name
        run: python set_machine_name.py fv-az1113-357
      - name: Run tracking benchmarks until 0.9.0
        run: |
          asv run -ev --append-samples --machine fv-az1113-357 2>&1 | tee log_$GITHUB_RUN_ID
      - name: Create html with all results
        run: |
          asv publish
      - uses: actions/upload-artifact@v4
        with:
          name: asv_benchmark_results
          path: |
            ./env
            ./html
            ./results
          compression-level: 9
      - name: Push new results and the log back to benchmarks repo
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            cd benchmarks_repo
            cp -r ../results .
            cp -r ../log_$GITHUB_RUN_ID ./logs/log_$GITHUB_RUN_ID
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add .
            git commit -m "Update benchmark results and logs ($GITHUB_RUN_ID)"
            git push origin main
      - name: Push html to gh-pages branch
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            git checkout gh-pages
            cp -r ../html/* .
            git add .
            git commit -m "Update benchmark HTML ($GITHUB_RUN_ID)"
            git push origin gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/main'
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
